stages:          # List of stages for jobs, and their order of execution
  - test
  - lint
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  services:
    - name: mongo:6.0-jammy
      alias: mongo
  variables:
    JWT_SECRET: "secret"
  script:
    - echo "Running unit tests..."
    - echo "$JWT_SECRET"
    - export JWT_SECRET=$JWT_SECRET
    - cd auth
    - npm install
    - npm run test

linter-job:
  stage: lint
  before_script:
    - npm i -g eslint
  script:
    - eslint ./src/*.ts