stages:          # List of stages for jobs, and their order of execution
  - test
  - build

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - cd auth
    - npm install
  script:
    - echo "Running unit tests..."
    - cd auth
    - npm run test
